[package]
name = "ark_fields"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = { version = "0.5" }
ark-test-curves = {version = "0.5.0", features = ["bls12_381_curve"]}
rand ={ version = "*"}
sha2 ={ version = "*"}
ark-serialize-derive = "0.4.2"
ark-serialize = "0.5"